w3:
  image: ci/w3
  volumes:
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "5002:8443" 
service:
  image: ci/service
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /shared/am/prod/db/snapshots:/snapshots
  ports:
    - "5001:8443"
db:
  image: ci/db
  volumes:
    - /shared/am/prod/db:/var/lib/mysql 
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "5005:3306"
