//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.27 at 09:56:44 PM EDT 
//


package com.sevtekin.am.common;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "categoryEntry",
    "ownerEntry"
})
@XmlRootElement(name = "CashEntry")
public class CashEntry {

    @XmlElement(name = "CategoryEntry", required = true)
    protected CategoryEntry categoryEntry;
    @XmlElement(name = "OwnerEntry", required = true)
    protected OwnerEntry ownerEntry;
    @XmlAttribute(name = "id", required = true)
    protected int id;
    @XmlAttribute(name = "amount", required = true)
    protected double amount;
    @XmlAttribute(name = "duedate", required = true)
    @XmlSchemaType(name = "date")
    protected Date duedate;
    @XmlAttribute(name = "actualdate")
    @XmlSchemaType(name = "date")
    protected Date actualdate;
    @XmlAttribute(name = "description")
    protected String description;

    public CategoryEntry getCategoryEntry() {
        return categoryEntry;
    }

    public void setCategoryEntry(CategoryEntry value) {
        this.categoryEntry = value;
    }

    public OwnerEntry getOwnerEntry() {
        return this.ownerEntry;
    }

    public int getId() {
        return id;
    }

    public void setId(int value) {
        this.id = value;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double value) {
        this.amount = value;
    }

    public Date getDuedate() {
        return duedate;
    }

     public void setDuedate(Date value) {
        this.duedate = value;
    }
  
    public Date getActualdate() {
        return actualdate;
    }

  
    public void setActualdate(Date value) {
        this.actualdate = value;
    }

	public void setOwnerEntry(OwnerEntry ownerEntry) {
		this.ownerEntry = ownerEntry;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
