//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.27 at 09:56:44 PM EDT 
//


package com.sevtekin.am.common;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sevtekin.am.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sevtekin.am.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeywordEntries }
     * 
     */
    public KeywordEntries createKeywordEntries() {
        return new KeywordEntries();
    }

    /**
     * Create an instance of {@link CategoryEntries }
     * 
     */
    public CategoryEntries createCategoryEntries() {
        return new CategoryEntries();
    }

    /**
     * Create an instance of {@link KeywordEntry }
     * 
     */
    public KeywordEntry createKeywordEntry() {
        return new KeywordEntry();
    }

    /**
     * Create an instance of {@link CashEntries }
     * 
     */
    public CashEntries createCashEntries() {
        return new CashEntries();
    }

    /**
     * Create an instance of {@link CashEntry }
     * 
     */
    public CashEntry createCashEntry() {
        return new CashEntry();
    }

    /**
     * Create an instance of {@link OwnerEntry }
     * 
     */
    public OwnerEntry createOwnerEntry() {
        return new OwnerEntry();
    }

    /**
     * Create an instance of {@link OwnerEntries }
     * 
     */
    public OwnerEntries createOwnerEntries() {
        return new OwnerEntries();
    }

    /**
     * Create an instance of {@link CategoryEntry }
     * 
     */
    public CategoryEntry createCategoryEntry() {
        return new CategoryEntry();
    }

}
