apiVersion: v1
kind: Service
metadata:
  name: am
  labels:
    app: am
spec:
  ports:
    - port: 3306
      name: amdb
    - port: 8443
      name: ambackend
    - port: 443
      name: amfrontend
  selector:
    app: am
  type: LoadBalancer
