FROM mysql 
MAINTAINER Sefa Sevtekin
ENV MYSQL_ROOT_PASSWORD=amdb
ENV MYSQL_USER=amdbuser
ENV MYSQL_PASSWORD=amdb
#ENV MYSQL_DATABASE=amdb
#COPY entry.sh /root/
#RUN chmod 744 /root/entry.sh
#ENTRYPOINT exec /root/entry.sh
#CMD ["/usr/sbin/mysqld"]
